apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: cert-manager-herissondev
 namespace: herissondev
spec:
 acme:
   email: aime.risson.1@gmail.com
   server: https://acme-v02.api.letsencrypt.org/directory # production
   privateKeySecretRef:
     name: cert-manager-herissondev-private-key # certificat
   solvers:
   - http01:
        ingress:
          class: traefik