apiVersion: apps/v1
kind: Deployment
metadata:
    name: herisson-dev
    namespace: herissondev
    labels:
        app: herisson-dev
spec:
    replicas: 1
    selector:
        matchLabels:
            app: herisson-dev
    template:
        metadata:
            labels:
                app: herisson-dev
        spec:
            containers:
                - name: herisson-dev
                  image: aimerisson/herisson.dev:latest
                  ports:
                      - containerPort: 4000

                  env:
                      -   name: SECRET_KEY_BASE
                          valueFrom:
                              secretKeyRef:
                                  name: herissondev-secret
                                  key: SECRET_KEY_BASE
                      -   name: PHX_HOST
                          # env is herisson.dev
                          value: herisson.dev

                  imagePullPolicy: Always
                  resources:
                      requests:
                          cpu: '500m'

