apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: herissondev-ingress-https
  namespace: herissondev
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`herisson.dev`)
      kind: Rule
      services:
        - name: herissondev-svc
          port: 4000
  tls:
    secretName: herissondev-wildcard-certificate-secret