apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: herissondev-ingress-https
  namespace: herissondev
spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`herisson.dev`)
      kind: Rule
      middlewares:
        - name: redirect-to-nonwww
          namespace: traefik
      services:
        - name: herissondev-svc
          port: 4000
  tls:
    secretName: herissondev-wildcard-certificate-secret
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-nonwww
  namespace: traefik
spec:
  redirectRegex:
    permanent: true
    regex: ^(?:https://)?(?:www\.)?(.+)
    replacement: https://${1}
