apiVersion: v1
kind: Service
metadata:
    name: herissondev-svc
    namespace: herissondev
spec:
    type: ClusterIP
    selector:
        app: herissondev-svc
    ports:
        - protocol: 'TCP'
          port: 4000
          targetPort: 4000
