name: herisson.dev continuous deployment

on:
  push:
    branches:
      - "main"

jobs:

  push-api:
    #needs: build-test
    runs-on: ubuntu-latest
    steps:
      # get commit hash for image label
      - id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2

        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: aimerisson/herisson.dev:${{ steps.commit.outputs.short }}